steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/elastic-ce-tools/esdiag/esdiag:latest",
        "-t",
        "us-west1-docker.pkg.dev/elastic-ce-tools/esdiag/esdiag:${_VERSION}",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-latest"
    args:
      ["push", "us-west1-docker.pkg.dev/elastic-ce-tools/esdiag/esdiag:latest"]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-versioned"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/elastic-ce-tools/esdiag/esdiag:${_VERSION}",
      ]

# Defaults, override with --substitutions flag
substitutions:
  _VERSION: "latest"
