steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west2-docker.pkg.dev/elastic-customer-eng/esdiag/esdiag:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west2-docker.pkg.dev/elastic-customer-eng/esdiag/esdiag:latest']
