# The bin/stack-local-setup.sh builds the required esdiag container and
# runs a minimal, security-disabled Elasticsearch and Kibana stack.
#
# Only use this for running esdiag on a local machine!
#
# Ensure you've allocated your container runtime virtual machine at least 8 GB
# of memory and as many CPU cores as you can spare for fast ingest performance.

name: esdiag
services:
  esdiag-webui:
    container_name: esdiag
    image: esdiag:latest
    depends_on:
      - esdiag-elasticsearch
      - esdiag-kibana
    environment:
      ESDIAG_OUTPUT_URL: http://esdiag-elasticsearch:9200
      ESDIAG_KIBANA_URL: http://localhost:5601
      LOG_LEVEL: info
    command: ["serve"]
    networks:
      - esdiag-net
    ports:
      - 3000:3000

  esdiag-elasticsearch:
    container_name: esdiag-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.2
    environment:
      - node.name=esdiag-node
      - cluster.name=esdiag-cluster
      - cluster.initial_master_nodes=esdiag-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
      # Workaround for MacOS 15.2 on M4: https://github.com/elastic/elasticsearch/issues/118583 and https://bugs.openjdk.org/browse/JDK-8345296
      - "_JAVA_OPTIONS=-XX:UseSVE=0"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdiag-data:/usr/share/elasticsearch/data
    networks:
      - esdiag-net
    ports:
      - 9200:9200

  esdiag-kibana:
    container_name: esdiag-kibana
    image: docker.elastic.co/kibana/kibana:8.18.2
    depends_on:
      - esdiag-elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://esdiag-elasticsearch:9200
    networks:
      - esdiag-net
    ports:
      - 5601:5601

volumes:
  esdiag-data:
    driver: local

networks:
  esdiag-net:
    driver: bridge
